var express = require("express");
var router = express.Router();
var Karyawan = require("./employees/karyawan");
var pilih = require("./employees/pilihnama");
var absences = require("./absences/absence");
var history = require("./history/absen");
var lines = require("./cms/line");
var machines = require("./cms/machine");
var grafik = require("./cms/grafik");
var shift = require("./shift/shift");
var position = require("./mapingpos/maping");
var parameters = require("./cms/parameters");
var schedules = require("./cms/schedule");
var planSchedule = require("./cms/planingSchedule");
var reservasi = require("./Tool/reservasi");
var grafikReservasi = require("./Tool/grafikReservasi");
var regrinding = require("./Tool/regrinding");
var grafikRegrinding = require("./Tool/grafikReg");
var planMonth = require("./cms/planMotnh");
var historySchedule = require("./cms/history");
var historyKuras = require("./cms/historyKuras");
var delivery = require("./Delivery/masterLine");
var masterTools = require("./Delivery/masterTool");
var kanban = require("./Delivery/kanban");
var fromGel = require("./Delivery/fromGel");
var laporanHarian = require("./LaporanHarian/laporan");
var category = require("./Category/category");
var stdCounter = require("./StdCounter/stdCounter");
var problem = require("./problem/problem");
var OEE = require("./LaporanHarian/oee");
var analisa = require("./analisa/analisa");
var history = require("./history/absen");
var historyProblem = require("./history/historyProblem");
var timerange = require("./TimeRange/index");
var machineOpNo = require("./MachineOpNo/machineop");
var Tools = require("./MasterTools/masterTools");
var masterLines = require("./MasterLines/index");
var masterMachines = require("./MasterMachines/index");
var coolant = require("./HistoryKuras/index");
var masterOli = require("./MasterOli/index");
var historyChemical = require("./HistoryChemical/HistoryChemical");

router.use("/employees", Karyawan);
router.use("/select", pilih);
router.use("/presence", absences);
router.use("/histories", history);
router.use("/lines", lines);
router.use("/machines", machines);
router.use("/grafik", grafik);
router.use("/shift", shift);
router.use("/position", position);
router.use("/parameters", parameters);
router.use("/schedules", schedules);
router.use("/planSchedule", planSchedule);
router.use("/reservasi", reservasi);
router.use("/grafikreservasi", grafikReservasi);
router.use("/regrinding", regrinding);
router.use("/grafikRegrinding", grafikRegrinding);
router.use("/planMonth", planMonth);
router.use("/historySchedule", historySchedule);
router.use("/historyKuras", historyKuras);
router.use("/delivery", delivery);
router.use("/masterTools", masterTools);
router.use("/kanban", kanban);
router.use("/kanbanFromGel", fromGel);
router.use("/tools", laporanHarian);
router.use("/category", category);
router.use("/laporan", stdCounter);
router.use("/problem", problem);
router.use("/oee", OEE);
router.use("/analisa", analisa);
router.use("/history-problem", historyProblem);
router.use("/masterTimerange", timerange);
router.use("/masterMachineOpNo", machineOpNo);
router.use("/masterToolsList", Tools);
router.use("/masterLines", masterLines);
router.use("/masterMachines", masterMachines);
router.use("/coolant", coolant);
router.use("/masterProblems", require("./MasterProblems/index"));
router.use("/pareto", require("./Pareto/index"));
router.use("/historySPV", require("./absenSPV/index"));
router.use("/nonshift", require("./nonshift/index"));
router.use("/masterOli", masterOli);
router.use("/pemakaianOli", require("./pemakaianOli/index"));
router.use("/parametersOptions", require("./Parameter/index"));
router.use("/masterOptions", require("./MasterOli/option"));
router.use("/historyChemical", historyChemical);
router.use("/masterNote", require("./notes/MasterNote"));
router.use("/reservasiChemical", require("./Reservasi/reservasi"));
router.use("/auth", require("./login/index"));
router.use("/gentani", require("./Gentani/index"));

module.exports = router;
